"""Add composition_id foreign key to PriceCap

Revision ID: 1a3fd941099b
Revises: 8ed64b6e24b4
Create Date: 2024-09-20 13:48:12.288401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3fd941099b'
down_revision = '8ed64b6e24b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composition_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'compositions', ['composition_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cap', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('composition_id')

    # ### end Alembic commands ###
