"""Add composition_id foreign key to PriceCap

Revision ID: 8ed64b6e24b4
Revises: b1bd3c57ae1d
Create Date: 2024-09-20 12:19:15.007336

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8ed64b6e24b4'
down_revision = 'b1bd3c57ae1d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composition_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_price_cap_composition_id', 'compositions', ['composition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cap', schema=None) as batch_op:
        batch_op.drop_constraint('fk_price_cap_composition_id', 'price_cap', type_='foreignkey')
        batch_op.drop_column('composition_id')
    # ### end Alembic commands ###

