"""Rename price to price_cap in price_cap_implants table

Revision ID: 9ba3db91419e
Revises: 9e9be651454e
Create Date: 2024-09-20 16:28:53.216155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba3db91419e'
down_revision = '9e9be651454e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cap_implants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_cap', sa.Numeric(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cap_implants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.drop_column('price_cap')

    # ### end Alembic commands ###
